# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/sample.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "User" do
    optional :user_name, :string, 1
    optional :introduction, :string, 2
    optional :age, :int64, 3
    repeated :educations, :message, 4, "User.Education"
    repeated :experiences, :message, 5, "User.Experience"
  end
  add_message "User.Education" do
    optional :school_name, :string, 1
  end
  add_message "User.Experience" do
    optional :company_name, :string, 1
  end
end

module Protos::SamplePB
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
  User::Education = Google::Protobuf::DescriptorPool.generated_pool.lookup("User.Education").msgclass
  User::Experience = Google::Protobuf::DescriptorPool.generated_pool.lookup("User.Experience").msgclass
end
